[package]
name = "dream"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dream-editor = { path = "./dream-editor", version = "0.1.0" }
dream-renderer = { path = "./dream-renderer", version = "0.1.0" }
dream-ecs = { path = "./dream-ecs", version = "0.1.0" }
dream-resource = { path = "./dream-resource", version = "0.1.0" }
dream-math = { path = "./dream-math", version = "0.1.0" }
shipyard = "0.6.2"
anyhow = "1.0"
cfg-if = "1"
winit = "0.28"
env_logger = "0.10"
log = "0.4"
wgpu = "0.15"
pollster = "0.3.0"
epi = "0.17.0"
bytemuck = { version = "1.12", features = ["derive"] }
boa_engine = { version = "0.16.0", features = ["console"] }
gc = "0.4.1"
boa_gc = "0.16.0"
rapier3d = "0.17.2"
rapier2d = "0.17.2"
cgmath = "0.18"
crossbeam-channel = "0.5"
tobj = { version = "3.2", features = ["async"] }
gltf = "1.1.0"
lazy_static = "1.4.0"
once_cell = "1.17.1"

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
reqwest = { version = "0.11" }
console_error_panic_hook = "0.1.6"
console_log = "1.0.0"
wgpu = { version = "0.15", features = ["webgl"]}
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.30"
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "Element",
    "Location",
]}

[workspace]
members = [
    "dream-editor",
    "dream-renderer",
    "dream-ecs",
    "dream-resource",
    "dream-math"
]
