[package]
name = "dream-ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
shipyard = "0.6.2"
cgmath = { workspace = true }
once_cell = { workspace = true }
dream-math = { workspace = true }
dream-resource = { workspace = true }