on:
  push:
    branches:
      - '**'
  pull_request:
    types: [ opened, reopened, closed, synchronize ]

# TODO: only allow for main on push
# TODO: create separate pipeline for pull request to create review app (https://github.com/marketplace/actions/manage-heroku-review-apps)
#  pull_request:
#    branches:
#      - '**'

name: CD Review App

jobs:
  deploy_web:
    name: Deploy Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jetli/wasm-pack-action@v0.4.0
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Add Toolchain
        working-directory: crates/dream-runner
        run: rustup component add rust-src --toolchain nightly-2022-12-12-x86_64-unknown-linux-gnu
      - name: Build web
        working-directory: crates/dream-runner
        run: rustup run nightly-2022-12-12 wasm-pack build --target web --out-dir ../../web/build --release
      - name: Delete web git ignore
        working-directory: web
        run: rm -rf .gitignore
      - name: Delete web/build git ignore
        working-directory: web/build
        run: rm -rf .gitignore
      - name: Deploy Heroku app
        uses: pmbanugo/heroku-review-app-actions@v2.0.0 # Uses the action
        id: deploy
        with:
          api-key: ${{ secrets.HEROKU_API_KEY }}
          pipeline-id: ${{ secrets.HEROKU_PIPELINE_ID }}
          base-name: getting-started
      - name: Get the review app url
        run: echo "The URL is ${{ steps.deploy.outputs.url }}"
#      - name: Comment on commit
#        uses: phulsechinmay/rewritable-pr-comment@v0.2.1
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          COMMENT_IDENTIFIER: "Deploy"
#          message: |
#            I deployed a review app for you to try out this pull request 👇🏽
#
#            Heroku App: ${{ steps.deploy.outputs.url }}