on:
  push:
    branches:
      - main
#      - '**'

name: CI

jobs:
  build_ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Add nightly toolchain component
        working-directory: crates/dream-runner
        run: rustup component add rust-src --toolchain nightly-2022-12-12-x86_64-unknown-linux-gnu
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
  build_web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jetli/wasm-pack-action@v0.4.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Add nightly toolchain component
        working-directory: crates/dream-runner
        run: rustup component add rust-src --toolchain nightly-2022-12-12-x86_64-unknown-linux-gnu
      - name: Build
        working-directory: crates/dream-runner
        run: rustup run nightly-2022-12-12 wasm-pack build --target web --out-dir ../../web/build --release
