name: Deploy
on:
  push:
    branches:
      - main
      - 5-python-script-component-system
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      #      - name: Build
      #        uses: actions-rs/cargo@v1
      #        with:
      #          command: build
      #          args: --release --all-features
      - name: Build web
        run: rustup run nightly-2022-12-12 wasm-pack build --target web --out-dir ../../web/build --release
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
