name: Deploy Web
on:
  push:
    branches:
      - main
      - 5-python-script-component-system
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jetli/wasm-pack-action@v0.4.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      #      - name: Build
      #        uses: actions-rs/cargo@v1
      #        with
      #          command: build
      #          args: --release --all-features
      - name: Add Toolchain
        working-directory: crates/dream-runner
        run: rustup component add rust-src --toolchain nightly-2022-12-12-x86_64-unknown-linux-gnu
      - name: Build web
        working-directory: crates/dream-runner
        run: rustup run nightly-2022-12-12 wasm-pack build --target web --out-dir ../../web/build --release
      - name: Delete web git ignore
        working-directory: web
        run: rm -rf .gitignore
      - name: Delete web/build git ignore
        working-directory: web/build
        run: rm -rf .gitignore
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
