[package]
name = "dream-tasks"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cfg-if = { workspace = true }
crossbeam-channel = { workspace = true }
once_cell = { workspace = true }
async-executor = { workspace = true }